version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8090:8090"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8090"
    environment:
      - DB_HOST=db
      - DB_NAME=apps
      - DB_USER=postgres
      - DB_PASS=superscretpassword
    depends_on:
      - db
      - cache
  cache:
   image: memcached
   ports:
     - "11211:11211"
   entrypoint:
    - memcached
    - -m 64


  db:
    image: postgres
    environment:
      - POSTGRES_DB=apps
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superscretpassword
