# Generated by Django 3.2.9 on 2021-12-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='content',
        ),
        migrations.AlterField(
            model_name='summary',
            name='articleUrl',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
